Accounts/urls.py
'''
Created on Apr 1, 2013

@author: Admin
'''
from django.conf.urls import patterns, url
from Accounts.views import member_list, view_profile, edit_profile

# url for account
urlpatterns = patterns('',
     url(r'^$', member_list),
     url(r'^(?P<member_id>\d+)-(?P<member_username>\w+)/$', view_profile),
     url(r'^edit_my_profile/$', edit_profile),
)

Quiz_Management/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import os

static = os.path.join(
    os.path.dirname(__file__), 'static'
)
image = os.path.join(
    os.path.dirname(__file__), 'image'
)

from Accounts.views import login_user, logout, signup, about, signup_success
from Class.views import create_class, create_class_success, classes, edit_class
from Quizz.views import *
from Quiz_Management.views import home

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	# home
    url(r'^$', home),
	url(r'^home/$', home),
    url(r'^about/$', about),

    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
         { 'document_root': static }),

    (r'^image/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': image}),
)

# account
urlpatterns += patterns('Accounts.views',
    url(r'^login/$', login_user),
    url(r'^logout/$', logout),
    url(r'^register/$', signup),
    url(r'./register/$', signup),
    url(r'^signup_success/$', signup_success),
    url(r'^member/', include('Accounts.urls')),
)

# classes
urlpatterns += patterns('',
    url(r'^class/([^\s]+)/$', classes),
    url(r'^create_class/$', create_class),
    url(r'^create_class_success/([^\s]+)/$', create_class_success),
    url(r'^edit_class/([^\s]+)/$', edit_class),
)

# quizzes
urlpatterns += patterns('',
    url(r'^create_quizz/([^\s]+)/$', create_quizz),
    url(r'^quizzes/([^\s]+)/$', quizzes),
    url(r'^doing_quizz/([^\s]+)/$', doing_quizz),
    url(r'^edit_quizz/([^\s]+)/$', edit_quizz),
)

# question and result
urlpatterns += patterns('',
    url(r'^create_questions/([^\s]+)/$', create_question),
    url(r'^edit_question/([^\s]+)/$', edit_question),
    url(r'^delete_question/([^\s]+)/$', delete_question),
    url(r'^result/([^\s]+)/([^\s]+)/([^\s]+)/([^\s]+)/$', result),
    url(r'^answer/([^\s]+)/$', answer),
)

Class/models.py
'''
models.py
'''
from django.db import models
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


#====Classes model=========================================
class Classes(models.Model):
    '''
    Model Classes
    '''
    objects = models.Manager()
    user = models.ForeignKey(User, \
        db_column='user_created_id', related_name='user')
    class_name = models.CharField(max_length=200)     #Name of class
    number_students = models.IntegerField(default=0)  #Number of students
    teacher_name = models.CharField(max_length=200)   #Teacher of class
    update_time = models.TimeField('Time published')  #Time of the last update
    update_date = models.DateField('Date published')  #Date of the last update
    students = models.ManyToManyField(User)  # Contain all students
    locked = models.BooleanField(default = False)

    def __unicode__(self):  # Show as title of this class
        return self.class_name


# RegistrationClassForm model to make and check form for class model
class RegistrationClassForm(forms.Form):
    '''
    Registration class form
    '''
    # All form in Registation class
    class_name = forms.CharField(label='Class name', max_length=200)
    number_students = forms.IntegerField(label='Number students')
    teacher_name = forms.CharField(label='Teacher name', max_length=200)


    # class Meta to show that the form get variables for model class
    class Meta:
        '''
        Meta class
        '''
        def __init__(self):
            pass
        # Definition the Form get data for model Classes
        model = Classes

    # Some common method
    def __len__(self, key):
        pass

    def __setitem__(self, name, item):
        pass

    def __delitem__(self, name):
        pass

    # function to check if the class_name in model Classes valid or not
    def clean_class_name(self):
        '''
        check class_name variable
        '''
        # Get class name entered by user
        class_name = self.cleaned_data['class_name']
        # Check class name is empty or not
        if not class_name:
            raise forms.ValidationError('Enter the name of class !')
        name_exist = Classes.objects.filter(class_name__iexact=class_name)
        # Check if the class name are like different class or not
        if len(name_exist) >= 1:
            raise ValidationError(\
                'That name already registerd for different class,\
                choose another one')
        return class_name

    # function to check if the number_students in model Classes valid or not
    def clean_number_students(self):
        '''
        check number students
        '''
        # Get number students from form
        number_students = self.cleaned_data['number_students']
        # Check if the number students is empty or not
        if not number_students:
            raise forms.ValidationError('Enter the number of students')
        # The number of student must NOT is negative integer and greater than 50
        if number_students > 50 or number_students <= 0:
            raise forms.ValidationError(\
                'The number of students must between 1 and 50')
        return number_students

    # function to check if the teacher_name in model Classes valid or not
    def clean_teacher_name(self):
        '''
        check teacher name
        '''
        teacher_name = self.cleaned_data['teacher_name']
        # It means teacher_name field is empty
        if not teacher_name:
            raise forms.ValidationError('Enter the name of teacher!')
        return teacher_name


# Check infor when user want edit infor of class but not change class_name
class EditClassInformationForm(forms.Form):
    '''
    edit class infor form
    '''
    # All form in Edit class form
    number_students = forms.IntegerField(label='Number students')
    teacher_name = forms.CharField(label='Teacher name', max_length=200)


    # class Meta to show that the form get variables for model class
    class Meta:
        '''
        class Meta
        '''
        def __init__(self):
            pass
        # Definition the Form get data for model Classes
        model = Classes

    # Some common method
    def __len__(self, key):
        pass

    def __setitem__(self, name, item):
        pass

    def __delitem__(self, name):
        pass

    # function to check if the number_students in model Classes valid or not
    def clean_number_students(self):
        '''
        check number students
        '''
        # Get number students from form
        number_students = self.cleaned_data['number_students']
        # Check if the number students is empty or not
        if not number_students:
            raise forms.ValidationError('Enter the number of students')
        # The number of student must NOT is negative integer and greater than 50
        if number_students > 50 or number_students <= 0:
            raise forms.ValidationError(\
                'The number of students must between 1 and 50')
        return number_students

    # function to check if the teacher_name in model Classes valid or not
    def clean_teacher_name(self):
        '''
        check teacher name
        '''
        teacher_name = self.cleaned_data['teacher_name']
        # It means teacher_name field is empty
        if not teacher_name:
            raise forms.ValidationError('Enter the name of teacher!')
        return teacher_name

Quizz/models.py
from django.db import models
from django import forms
from django.core.validators import ValidationError
from Class.models import Classes

# Create quizz model.


class Quizzes(models.Model):
    objects = models.Manager()
    in_class = models.ForeignKey(Classes, db_column='in_class', related_name='Classes')		# Class of this quizz.
    title = models.CharField(max_length=200)						# Title of this quizz
    update_time = models.TimeField('date published')				# The time the Quizz was created
    update_date = models.DateField('Date published')				# The date the Quizz was created
    time_limit = models.IntegerField()								# Limited time to do this quizz.
    number_questions = models.IntegerField()						# Number of questions in this Quizz

    def __unicode__(self):
        return self.title

# Create Form of Quizz.


class MakeQuizzForm(forms.Form):
    title = forms.CharField(label='Title', max_length=200)				# Make form for title
    time_limit = forms.IntegerField(label='Time limit (mins)')		# Make form for time limit

    class Meta:
        model = Quizzes

    def clean_title(self):
        title = self.cleaned_data['title']

        if not title:													# Check that title is not null.
            raise forms.ValidationError('Enter the title of Quizzes !')		# Return error notification when you didn't enter title.
        title_exist = Quizzes.objects.filter(title__iexact=title)		# Check to make sure that title of class is unique.

        if len(title_exist) >= 1:
            raise ValidationError('That title already maked for different Quizzes, choose another one')		# Return error notification when this title, the same as exist title in database
        return title

# Create Questions models.


class Questions(models.Model):
    objects = models.Manager()
    quizz = models.ForeignKey(Quizzes, related_name='Quizzes')				# quizz of this question.
    ques = models.TextField(max_length=1000)		# Question component of question packet.
    ans1 = models.CharField(max_length=500)			# The first answer to choose.
    ans2 = models.CharField(max_length=500)			# The second answer to choose.
    ans3 = models.CharField(max_length=500)			# The third answer to choose.
    ans4 = models.CharField(max_length=500)			# The fourth answer to choose.
    correct_ans = models.IntegerField()				# The index of correct answer.

# Create Question form.


class MakeQuestionsForm(forms.Form):
    ques = forms.CharField(label='Question', max_length=1000)		# Question component of question packet.
    ans1 = forms.CharField(label='answer 1', max_length=500)			# The first answer to choose.
    ans2 = forms.CharField(label='answer 2', max_length=500)			# The second answer to choose.
    ans3 = forms.CharField(label='answer 3', max_length=500)			# The third answer to choose.
    ans4 = forms.CharField(label='answer 4', max_length=500)			# The fourth answer to choose.
    correct_ans = forms.IntegerField(label='answer correct')			# The index of correct answer.

templates/edit/edit_class.html
{% extends "base.html" %}

<!--Title-->
{% block title %} Edit {{Class.class_name}} {% endblock %}

<!--body-->
{% block content_before_login %}
    <center><h3>Sorry! You are not in account<br />Please <a href="/login/">log in </a> or <a href="register"> create new account </a>to use this page .</h3></center>
{% endblock %}


<!-- Forms
================================================== -->
{% block content_after_login %}
	<section id="forms">
		<div class="page-header" align="center">
			<font color="#66CC99"><h1>{{Class.class_name}}</h1></font>
		</div>
		
		{% if User = Class.user %}
		
		<div class="container">
			<div class ="span7 offset2">
				<div class = "row-fluid" align = "center">
					<form class = "well form-horizontal focused" action = "." method = "post" align = "center"> {% csrf_token %}
						<legend><b><font color="#FF9966">Changing informations of class {{Class.class_name}}</font></b></legend>
						<font color="#FF0000"><em>{{state}}</em></font><br /><br />
						<style type="text/css">
							.errorlist li {
								font-size: 12px;
								color: red;
								display: block;
							}
						</style>
						<table class="table table-condensed " align="center" >
							<tr>
								<th><label for="id_class_name"><h5>Class's Name</h5></label></th>
								<td>:</td>
								<td><input type="text" id="id_class_name" name="class_name" value="{{Class.class_name}}" /></td>
							</tr>
							<tr>
								<th><label for="id_number_students"><h5>No. Students</h5></label></th>
								<td>:</td>
								<td><input type="number" id="id_number_students" name="number_students" value="{{Class.number_students}}" /></td>
							</tr>
							<tr>
								<th><label for="id_teacher_name"><h5>Teacher's Name</h5></label></th>
								<td>:</td>
								<td><input type="text" id="id_teacher_name" name="teacher_name" value="{{Class.teacher_name}}" /></td>
							</tr>
							
							<tr>
								<th><h5>Account of Teacher</h5></th>
								<td>:</td>
								<td><font color="#0033FF">{{Class.user.username}}</font></td>
							</tr>
						</table>
						<button type="submit" class="btn btn-success"><i class="icon icon-ok"></i> Change</button>
						<a href="/class/{{Class.id}}/"><button type="button" class="btn btn-warning"><i class="icon icon-remove-sign"></i> Cancel</button></a>
						
					</form>
				</div>
			</div>
		</div>
		{% else %}
			<center><h4>You don't have permirsion to change data of this class!</h4></center>
		{% endif %}
	</section>
{% endblock %}

templates/edit/edit_profile.html
{% extends "base.html" %}

<!--Title-->
{% block title %} Edit {{Classes_list.class_name}} {% endblock %}

<!--body-->
{% block content_before_login %}
    <center><h3>Sorry! You are not in account<br />Please <a href="/login/">log in </a> or <a href="register"> create new account </a>to use this page .</h3></center>
{% endblock %}


<!-- Forms
================================================== -->
{% block content_after_login %}
	<section id="forms">
		<div class="page-header" align="center">
			<font color="#66CC99"><h1>{{user.username}}</h1></font>
		</div>
		
		<div class="container">
			<div class ="span7 offset2">
				<div class = "row-fluid" align = "center">
					<form class = "well form-horizontal focused" action = "." method = "post" align = "center"> {% csrf_token %}
						<legend><b><font color="#FF9966">Changing profile {{user.username}}</font></b></legend>
						<style type="text/css">
							.errorlist li {
								font-size: 12px;
								color: red;
								display: block;
							}
						</style>
						<table class="table table-condensed " align="center" >
							{{ form.as_table }}
						</table>
						<button type="submit" class="btn btn-success"><i class="icon icon-ok"></i> Change</button>
						<a href="/member/{{User.id}}-{{User.username}}/" class="btn btn-warning"><i class="icon icon-remove-sign"></i> Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

templates/edit/edit_question.html
{% extends "base.html" %}

<!--Title-->
{% block title %}Edit Question{% endblock %}

<!--body-->
{% block content_before_login %}
	<center><h3>You are currently not logged in! <br />Please <a href="/login/">log in</a> to create your questions !</h3></center>
{% endblock %}

{% block content_after_login %}
<div class = "container">
	<div class ="span7 offset2">
		<div class = "row-fluid" align = "center">
			<form class = "well form-horizontal focused" action = "." method = "post" align = "center">
            {% csrf_token %}
			  <legend><b>Edit question in <a href="/quizzes/{{Quizzes.id}}/">{{Quizz.title}} Quizzes</a></b></legend>
               	<style type="text/css">
					.errorlist li {
						font-size: 12px;
						color: red;
						display: block;
					}
				</style>
				<table class = "table">
                	<tr>
                    	<td>
                        	<h5>Question</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	<textarea class="input-xlarge" rows = "2.5" type="text" name="ques" id="ques" >{{Question.ques}}</textarea>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                        	<h5>Answer 1</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	<textarea class="input-xlarge" rows = "1.5" type="text" name="ans1" id="id_ans1" >{{Question.ans1}}</textarea>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                        	<h5>Answer 2</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	
                        	<textarea class="input-xlarge" rows = "1.5" type="text" name="ans2" id="ans2" >{{Question.ans2}}</textarea>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                        	<h5>Answer 3</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	<textarea class="input-xlarge" rows = "1.5" type="text" name="ans3" id="ans3">{{Question.ans3}}</textarea>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                        	<h5>Answer 4</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	<textarea class="input-xlarge" rows = "1.5" type="text" name="ans4" id="ans4">{{Question.ans4}}</textarea>
                        </td>
                    </tr>
                    <tr>
                    	<td>
                        	<h5>The correct answer</h5>
                        </td>
                    	<td>:</td>
                        <td>
                        	<select id="correct_ans" name="correct_ans">
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                            </select> 
                        </td>
                    </tr>
                    <p style = "color: red; "> {{state}} </p>
                </table>
					<button type="submit" class="btn btn-success"><i class="icon icon-ok"></i> Change</button>
					<a href="/quizzes/{{Quizz.id}}" class="btn btn-warning"><i class="icon icon-remove-sign"></i> Cancel</a> </br></br>
			</form>
		</div>	
	</div>
</div>
{% endblock %}

templates/edit/edit_quizz.html
{% extends "base.html" %}

<!--Title-->
{% block title %} Edit {{Quizz.title}} {% endblock %}

<!--body-->
{% block content_before_login %}
    <center><h3>Sorry! You are not in account<br />Please <a href="/login/">log in </a> or <a href="register"> create new account </a>to use this page .</h3></center>
{% endblock %}

{% block content_after_login %}
<!-- Forms
================================================== -->
<section id="forms">
    <div class="page-header" align="center">
    	<font color="#66CC99"><h1>{{Quizz.title}}</h1></font>
    </div>
    
    {% if User = Classes.user %}
    
    <div class="container">
    	<div class ="span7 offset2">
			<div class = "row-fluid" align = "center">
				<form class = "well form-horizontal focused" action = "." method = "post" align = "center"> {% csrf_token %}
                	<legend><b><font color="#FF9966">Changing informations of quizz {{Quizz.title}}</font></b></legend>
                    <style type="text/css">
						.errorlist li {
							font-size: 12px;
							color: red;
							display: block;
						}
					</style>
                    <table class="table table-condensed " align="center" >
                    	<tr>
                            <td><label for="id_class_name"><h5>Title</h5></label></td>
                            <td>:</td>
                            <td><input type="text" id="id_title" name="title" value="{{Quizz.title}}" /></td>
                        </tr>
                        <tr>
                            <td><label for="id_number_students"><h5>Time_limit (mins)</h5></label></td>
                            <td>:</td>
                            <td><input type="number" id="id_time_limit" name="time_limit" value="{{Quizz.time_limit}}" /></td>
                        </tr>
                       
                    </table>
                    <button type="submit" class="btn btn-success"><i class="icon icon-ok"></i> Change</button>
                    <a href="/quizzes/{{Quizz.id}}/"><button type="button" class="btn btn-warning"><i class="icon icon-remove-sign"></i> Cancel</button></a>
                    
                </form>
            </div>
        </div>
    </div>
    {% else %}
    	<center><h4>You don't have permirsion to change data of this quizz!</h4></center>
    {% endif %}
{% endblock %}